// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// Read provides a mock function with given fields: socketAddress
func (_m *Listener) Read(socketAddress string) ([]byte, error) {
	ret := _m.Called(socketAddress)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(socketAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(socketAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
