// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Write provides a mock function with given fields: socketAddress, data
func (_m *Writer) Write(socketAddress string, data []byte) error {
	ret := _m.Called(socketAddress, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(socketAddress, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
